declare const rexFirst = "http://underlay.org/ns/rex#first", rexLast = "http://underlay.org/ns/rex#last", rexGreatest = "http://underlay.org/ns/rex#greatest", rexLeast = "http://underlay.org/ns/rex#least", rexEarliest = "http://underlay.org/ns/rex#earliest", rexLatest = "http://underlay.org/ns/rex#latest", rexAll = "http://underlay.org/ns/rex#all", rexAny = "http://underlay.org/ns/rex#any";
export declare const defaultSort = "http://underlay.org/ns/rex#first";
export declare type Sort = typeof rexFirst | typeof rexLast | typeof rexGreatest | typeof rexLeast | typeof rexEarliest | typeof rexLatest | typeof rexAll | typeof rexAny;
export declare const rex: {
    in: "http://underlay.org/ns/rex#in";
    key: "http://underlay.org/ns/rex#key";
    with: "http://underlay.org/ns/rex#with";
    meta: "http://underlay.org/ns/rex#meta";
    sort: "http://underlay.org/ns/rex#sort";
    first: "http://underlay.org/ns/rex#first";
    last: "http://underlay.org/ns/rex#last";
    greatest: "http://underlay.org/ns/rex#greatest";
    least: "http://underlay.org/ns/rex#least";
    earliest: "http://underlay.org/ns/rex#earliest";
    latest: "http://underlay.org/ns/rex#latest";
    all: "http://underlay.org/ns/rex#all";
    any: "http://underlay.org/ns/rex#any";
};
export declare const xsd: {
    string: "http://www.w3.org/2001/XMLSchema#string";
    date: "http://www.w3.org/2001/XMLSchema#date";
    dateTime: "http://www.w3.org/2001/XMLSchema#dateTime";
    boolean: "http://www.w3.org/2001/XMLSchema#boolean";
    decimal: "http://www.w3.org/2001/XMLSchema#decimal";
    float: "http://www.w3.org/2001/XMLSchema#float";
    double: "http://www.w3.org/2001/XMLSchema#double";
    integer: "http://www.w3.org/2001/XMLSchema#integer";
    positiveInteger: "http://www.w3.org/2001/XMLSchema#positiveInteger";
    nonPositiveInteger: "http://www.w3.org/2001/XMLSchema#nonPositiveInteger";
    negativeInteger: "http://www.w3.org/2001/XMLSchema#negativeInteger";
    nonNegativeInteger: "http://www.w3.org/2001/XMLSchema#nonNegativeInteger";
    long: "http://www.w3.org/2001/XMLSchema#long";
    int: "http://www.w3.org/2001/XMLSchema#int";
    short: "http://www.w3.org/2001/XMLSchema#short";
    byte: "http://www.w3.org/2001/XMLSchema#byte";
    unsignedLong: "http://www.w3.org/2001/XMLSchema#unsignedLong";
    unsignedInt: "http://www.w3.org/2001/XMLSchema#unsignedInt";
    unsignedShort: "http://www.w3.org/2001/XMLSchema#unsignedShort";
    unsignedByte: "http://www.w3.org/2001/XMLSchema#unsignedByte";
};
export declare const rdf: {
    type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type";
    langString: "http://www.w3.org/1999/02/22-rdf-syntax-ns#langString";
};
export {};
